force-app/main/default/objects/CommercialTeam__c/CommercialTeam__c.object-meta.xml
<CustomObject>
    <description>Represents a group of users responsible for sales.</description>
    <label>Commercial Team</label>
    <nameField>
        <label>Commercial Teams</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommercialTeam__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Specifies the Team`s Country</description>
    <inlineHelpText>Specifies the Team`s Country</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommercialTeam__c/fields/Employee_Range__c.field-meta.xml
<CustomField>
    <fullName>Employee_Range__c</fullName>
    <label>Employee Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Employee_Range</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommercialTeam__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Record unique identifier</description>
    <formula>TEXT(Product_Interest__c) &amp; &apos;-&apos; &amp; TEXT(Country_Code__c) &amp; &apos;-&apos; &amp; TEXT(Employee_Range__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommercialTeam__c/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <description>Main Product of interest</description>
    <label>Product Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deals_Counter__c/Deals_Counter__c.object-meta.xml
<CustomObject>
    <description>Count the number of deals assigned to a team member.</description>
    <label>Deals Counter</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Counter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deals_Counter__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deals_Counter__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Deals_Counter__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>Team_Member__c</referenceTo>
    <relationshipLabel>Deals Counters</relationshipLabel>
    <relationshipName>Deals_Counters</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Product Interest</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>User that are part of a Commercial Team.</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Commercial_Team__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Reference to the Commercial Team</description>
    <label>Commercial Team</label>
    <referenceTo>CommercialTeam__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Employee_Range.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-100</fullName>
    </customValue>
    <customValue>
        <fullName>101-500</fullName>
    </customValue>
    <customValue>
        <fullName>501+</fullName>
    </customValue>
    <masterLabel>Employee Range</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Meal Voucher</fullName>
    </customValue>
    <customValue>
        <fullName>Gift</fullName>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Incentivos</fullName>
    </customValue>
    <customValue>
        <fullName>Beneficios</fullName>
    </customValue>
    <customValue>
        <fullName>Natal</fullName>
    </customValue>
    <masterLabel>Product Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadAssignmentService.cls
public with sharing class LeadAssignmentService implements Assignment {

    private Repository teamMemberRepository;
    private Repository dealsCounterRepository;

    public LeadAssignmentService() {
        this.teamMemberRepository = new TeamMemberRespository();
        this.dealsCounterRepository = new DealCounterRepository();
        
    }

    public List<Lead> process (List<SObject> records) {
        List<Lead> leads = getLeadsToProcess(records);
        Map<String, Lead> leadMap = buildLeadMappedByKey(leads);
        List<Team_Member__c> teamMembers = getAvailableTeamMembers(leadMap);
        List<Deals_Counter__c> dealsCounters = getDealsCounters(teamMembers);
        System.debug('Deals Counters: ' + dealsCounters);
        List<TeamMemberCounter> teamMemberCounters = buildTeamMemberCounters(teamMembers, dealsCounters);
        System.debug('teamMemberCounters: ' + teamMemberCounters);
        List<Lead> processedLeads = assignLeadsToTeamMembers(leads, teamMembers, teamMemberCounters);
        System.debug('Processed Leads: ' + processedLeads);
        if(processedLeads != null && !processedLeads.isEmpty()) {
            return (List<SObject>) processedLeads;
        }
        return new List<Lead>();
    }

    private List<Team_Member__c> getAvailableTeamMembers(Map<String, Lead> leadMap) {
        return ((TeamMemberRespository)this.teamMemberRepository)
            .findByCommercialTeamKey(new List<String>(leadMap.keySet()));
    }

    private List<Deals_Counter__c> getDealsCounters(List<Team_Member__c> teamMembers) {
        List<String> dealsCounterKeys = buildDealsCountKeysFromTeamMembers(teamMembers);
        System.debug('Team Members: ' + teamMembers);
        System.debug('Deals Counter Keys: ' + dealsCounterKeys);
        return ((DealCounterRepository)this.dealsCounterRepository).findByKey(dealsCounterKeys);
    }

    private List<Lead> assignLeadsToTeamMembers(List<Lead> leads, List<Team_Member__c> teamMembers, List<TeamMemberCounter> teamMemberCounters) {
        Map<Id, TeamMemberCounter> tmCounterMap = new Map<Id, TeamMemberCounter>();
        for (TeamMemberCounter tmc : teamMemberCounters) {
            tmCounterMap.put(tmc.teamMemberId, tmc);
        }
        Map<String, List<Id>> keyToTeamMemberIds = new Map<String, List<Id>>();
        for (Team_Member__c tm : teamMembers) {
            String key = tm.Commercial_Team__r.Key__c;
            if (!keyToTeamMemberIds.containsKey(key)) {
                keyToTeamMemberIds.put(key, new List<Id>());
            }
            keyToTeamMemberIds.get(key).add(tm.Id);
        }
        List<Deals_Counter__c> countersToUpdate = new List<Deals_Counter__c>();
        for (Lead l : leads) {
            String key = l.Product_Interest__c + '-' + l.Country_Code__c + '-' + l.Employee_Range__c;
            List<Id> possibleTms = keyToTeamMemberIds.get(key);
            if (possibleTms == null || possibleTms.isEmpty()) {
                continue;
            }
            TeamMemberCounter chosen = null;
            for (Id tmId : possibleTms) {
                TeamMemberCounter tmc = tmCounterMap.get(tmId);
                if (chosen == null || tmc.counter < chosen.counter) {
                    chosen = tmc;
                }
            }
            if (chosen != null) {
                l.OwnerId = chosen.userId;
                chosen.counter += 1;
                // Atualiza Deals_Counter__c
                countersToUpdate.add(new Deals_Counter__c(Id=chosen.dealCounter, Count__c=chosen.counter));
            }
        }

        if (!countersToUpdate.isEmpty()) {
            update countersToUpdate;
        }

        return leads;
    }

    private List<Lead> getLeadsToProcess(List<SObject> records) {
        List<Lead> leads = new List<Lead>();
        for (SObject record : records) {
            if (record instanceof Lead) {
                leads.add((Lead) record);
            }
        }
        return leads;
    }

    private Map<String, Lead> buildLeadMappedByKey(List<Lead> lead) {
        Map<String, Lead> leadMap = new Map<String, Lead>();
        for (Lead l : lead) {
            String key = l.Product_Interest__c + '-' + l.Country_Code__c + '-' + l.Employee_Range__c;
            leadMap.put(key, l);
        }
        return leadMap;
    }

    private List<String> buildDealsCountKeysFromTeamMembers(List<Team_Member__c> teamMembers) {
        List<String> keys = new List<String>();
        Date today = Date.today();
        String year = String.valueOf(today.year());
        String month = String.valueOf(today.month());

        if (month.length() == 1) {
            month = '0' + month;
        }

        String currentMonth = year + '/' + month;
        
        for (Team_Member__c tm : teamMembers) {
            keys.add(tm.Id + '-' + currentMonth);
        }
        return keys;
    }

    private List<TeamMemberCounter> buildTeamMemberCounters(List<Team_Member__c> teamMembers, List<Deals_Counter__c> dealsCounters) {
        Map<Id, Deals_Counter__c> teamMemberIdToCounter = new Map<Id, Deals_Counter__c>();
        for (Deals_Counter__c dc : dealsCounters) {
           
            teamMemberIdToCounter.put(dc.Team_Member__c, dc);
        }
        List<TeamMemberCounter> teamMemberCounters = new List<TeamMemberCounter>();
        for (Team_Member__c tm : teamMembers) {
            if (!teamMemberIdToCounter.containsKey(tm.Id)) {
                continue; // Skip if no counter found for the team member
            }
            System.debug('Team Member: ' + tm.Id + ', User: ' + tm.User__c);
            Deals_Counter__c counter = teamMemberIdToCounter.get(tm.Id);
            teamMemberCounters.add(new TeamMemberCounter(tm.Id, counter.Id, tm.User__c, counter.Count__c));
        }
        return teamMemberCounters;
    }

    public class TeamMemberCounter {
        public Id teamMemberId;
        public Id dealCounter;
        public Id userId;
        public Decimal counter;

        public TeamMemberCounter(Id teamMemberId, Id dealCounter, Id userId, Decimal counter) {
            this.teamMemberId = teamMemberId;
            this.dealCounter = dealCounter;
            this.userId = userId;
            this.counter = counter;
        }
    }
}