force-app/main/default/objects/Absence__c/Absence__c.object-meta.xml
<CustomObject>
    <label>Absence</label>
    <nameField>
        <displayFormat>ABS-{0000}</displayFormat>
        <label>Absence Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Absences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Absence__c/fields/Is_Returned__c.field-meta.xml
<CustomField>
    <fullName>Is_Returned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Returned?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Absence__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>Team_Member__c</referenceTo>
    <relationshipLabel>Absences</relationshipLabel>
    <relationshipName>Absences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommercialTeam__c/CommercialTeam__c.object-meta.xml
<CustomObject>
    <description>Represents a group of users responsible for sales.</description>
    <label>Commercial Team</label>
    <nameField>
        <label>Commercial Teams</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommercialTeam__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Specifies the Team`s Country</description>
    <inlineHelpText>Specifies the Team`s Country</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommercialTeam__c/fields/Employee_Range__c.field-meta.xml
<CustomField>
    <fullName>Employee_Range__c</fullName>
    <label>Employee Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Employee_Range</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommercialTeam__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Record unique identifier</description>
    <formula>TEXT(Product_Interest__c) &amp; &apos;-&apos; &amp; TEXT(Country_Code__c) &amp; &apos;-&apos; &amp; TEXT(Employee_Range__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommercialTeam__c/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <description>Main Product of interest</description>
    <label>Product Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Interest</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>User that are part of a Commercial Team.</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Commercial_Team__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Reference to the Commercial Team</description>
    <label>Commercial Team</label>
    <referenceTo>CommercialTeam__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Employee_Range.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-100</fullName>
    </customValue>
    <customValue>
        <fullName>101-500</fullName>
    </customValue>
    <customValue>
        <fullName>501+</fullName>
    </customValue>
    <masterLabel>Employee Range</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Interest.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Meal Voucher</fullName>
    </customValue>
    <customValue>
        <fullName>Gift</fullName>
    </customValue>
    <customValue>
        <fullName>Travel</fullName>
    </customValue>
    <customValue>
        <fullName>Incentivos</fullName>
    </customValue>
    <customValue>
        <fullName>Beneficios</fullName>
    </customValue>
    <customValue>
        <fullName>Natal</fullName>
    </customValue>
    <masterLabel>Product Interest</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TeamMemberRespository.cls
public with sharing class TeamMemberRespository implements Repository {

    public SObject findById(String Id) {
        Team_Member__c result = [
            SELECT Id, Commercial_Team__c
            FROM Team_Member__c
            WHERE Id = :Id
        ];
        return (SObject) result;
    }

    // Método utilitário extra, não faz parte da interface
    public List<Team_Member__c> findByCommercialTeamKey(List<String> employeeRanges, List<String> countryCodes, List<String> productInterests ) {
        return [
            SELECT Id, Commercial_Team__c, User__c, Commercial_Team__r.Key__c, Counter__c
            FROM Team_Member__c
            WHERE Commercial_Team__r.Country_Code__c IN :countryCodes
            AND Commercial_Team__r.Employee_Range__c IN :employeeRanges
            AND Commercial_Team__r.Product_Interest__c IN :productInterests
            AND Id NOT IN (SELECT Team_Member__c 
                                FROM Absence__c 
                                WHERE
                                    Start_Date__c <= :System.today() 
                                    AND End_Date__c >= :System.today()
                                    AND Is_Returned__c = false
                            )
        ];
    }

    public void insertRecords(List<SObject> records) {
        List<Team_Member__c> teamMembers = new List<Team_Member__c>();
        for (SObject s : records) {
            if (s instanceof Team_Member__c) {
                teamMembers.add((Team_Member__c)s);
            }
        }
        if (!teamMembers.isEmpty()) {
            insert teamMembers;
        }
    }

    public void updateRecords(List<SObject> records) {
        List<Team_Member__c> teamMembers = new List<Team_Member__c>();
        for (SObject s : records) {
            if (s instanceof Team_Member__c) {
                teamMembers.add((Team_Member__c)s);
            }
        }
        if (!teamMembers.isEmpty()) {
            update teamMembers;
        }
    }

    public void deleteRecords(List<SObject> records) {
        List<Team_Member__c> teamMembers = new List<Team_Member__c>();
        for (SObject s : records) {
            if (s instanceof Team_Member__c) {
                teamMembers.add((Team_Member__c)s);
            }
        }
        if (!teamMembers.isEmpty()) {
            delete teamMembers;
        }
    }

    public void upsertRecords(List<SObject> records) {
        List<Team_Member__c> teamMembers = new List<Team_Member__c>();
        for (SObject s : records) {
            if (s instanceof Team_Member__c) {
                teamMembers.add((Team_Member__c)s);
            }
        }
        if (!teamMembers.isEmpty()) {
            upsert teamMembers;
        }
    }
}