force-app/main/default/objects/Deals_Counter__c/Deals_Counter__c.object-meta.xml
<CustomObject>
    <description>Count the number of deals assigned to a team member.</description>
    <label>Deals Counter</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Counter Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deals_Counter__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deals_Counter__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Deals_Counter__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>Team_Member__c</referenceTo>
    <relationshipLabel>Deals Counters</relationshipLabel>
    <relationshipName>Deals_Counters</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <description>User that are part of a Commercial Team.</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DealCounterRepository.cls
public with sharing class DealCounterRepository implements Repository {
    public DealCounterRepository() {

    }

    public SObject findById(String Id) {

        Deals_Counter__c result = [
            SELECT Id, Name, OwnerId, Count__c, Team_Member__c, Key__c
            FROM Deals_Counter__c
            WHERE Id = :Id
        ];

        return (SObject) result;
    }

    public List<Deals_Counter__c> findByKey(List<String> keys) {
        return [
            SELECT Id, Name, OwnerId, Count__c, Team_Member__c, Key__c
            FROM Deals_Counter__c
            WHERE Key__c IN :keys
        ];
    }

    public void insertRecords(List<SObject> records) {
        List<Deals_Counter__c> deals = new List<Deals_Counter__c>();
        for (SObject s : records) {
            if (s instanceof Deals_Counter__c) {
                deals.add((Deals_Counter__c)s);
            }
        }
        if (!deals.isEmpty()) {
            insert deals;
        }
    }

    public void updateRecords(List<SObject> records) {
        List<Deals_Counter__c> deals = new List<Deals_Counter__c>();
        for (SObject s : records) {
            if (s instanceof Deals_Counter__c) {
                deals.add((Deals_Counter__c)s);
            }
        }
        if (!deals.isEmpty()) {
            update deals;
        }
    }

    public void deleteRecords(List<SObject> records) {
        List<Deals_Counter__c> deals = new List<Deals_Counter__c>();
        for (SObject s : records) {
            if (s instanceof Deals_Counter__c) {
                deals.add((Deals_Counter__c)s);
            }
        }
        if (!deals.isEmpty()) {
            delete deals;
        }
    }

    public void upsertRecords(List<SObject> records) {
        List<Deals_Counter__c> deals = new List<Deals_Counter__c>();
        for (SObject s : records) {
            if (s instanceof Deals_Counter__c) {
                deals.add((Deals_Counter__c)s);
            }
        }
        if (!deals.isEmpty()) {
            upsert deals;
        }
    }
}